apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
      - image: telegraf:latest
        name: telegraf
        resources: {}
      restartPolicy: Always
status: {}
