---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-slow-logs-config
data:
  initdb.sql: |
    SET GLOBAL slow_query_log = 'ON';
    SET GLOBAL long_query_time = 5;
    SET GLOBAL slow_query_log_file = '/var/log/mysql_slow.log';